source 'https://rubygems.org'

ruby '3.1.1'

gem 'rake'
gem 'hanami'
# gem 'hanami-model', git: 'https://github.com/hanami/model.git', require: false

# gem 'pg'

gem 'vite_ruby', path: '../../vite_ruby'

# gem 'vite_hanami', path: '../../vite_hanami'
gem 'vite_hanami'

group :development do
  # Code reloading
  # See: https://guides.hanamirb.org/projects/code-reloading
  gem 'shotgun', platforms: :ruby
  gem 'hanami-webconsole'
end

group :test, :development do
  gem 'dotenv'
  gem 'pry-byebug'
end

group :test do
  gem 'rspec'
  gem 'capybara'
end

group :production do
  gem 'puma'
end
