# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

Rake::Task['assets:precompile'].enhance do |task|
  Dir.chdir(Rails.root.join('example_engine')) {
    _, stderr, status = ViteRuby::IO.capture("VITE_RUBY_VITE_BIN_PATH=#{Rails.root.join(ViteRuby.config.vite_bin_path)} bin/vite build")
    raise stderr unless status.success?
  }
end
