source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in administrator.gemspec.
gemspec

# To use a debugger
# gem 'byebug', group: [:development, :test]
