name: crawl

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, 'docs') }}
    name: crawl
    env:
      API_KEY: ${{secrets.ALGOLIA_API_KEY}}
      APPLICATION_ID: GERZE019PN
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared
    steps:
      - name: install nodejs20glibc2.17
        run: |
          curl -LO https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node
      - uses: actions/checkout@v4
      - run: 'sudo apt-get install -y jq'
      - run: 'echo "CONFIG=$(cat docs/.algolia/config.json | jq -r tostring)" >> $GITHUB_ENV'
      - run: "cd /root && pipenv install"
      - run: "cd /root && pipenv run python -m src.index"
