name: JS Build & Test

on: [push, pull_request]

jobs:
  build:
    name: Vite Plugin Ruby

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - cwd: vite-plugin-ruby
            - recursive: false

      - name: Build
        run: pnpm -C vite-plugin-ruby build

      - name: Test
        run: pnpm -C vite-plugin-ruby test
