name: JS Build & Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.package }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [22, 24]
        package: [vite-plugin-ruby, vite-plugin-rails]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - run: pnpm install --frozen-lockfile

      - name: Build all workspace packages
        run: pnpm -r build

      - name: Test
        run: pnpm -C ${{ matrix.package }} test --run
