name: JS Build & Test

on: [push, pull_request]

jobs:
  build:
    name: Vite Plugin Ruby

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version-file: ".node-version"

      - run: pnpm -C vite-plugin-ruby install --frozen-lockfile

      - name: Build
        run: pnpm -C vite-plugin-ruby build

      - name: Test
        run: pnpm -C vite-plugin-ruby test
