name: JS Build & Test

on: [push, pull_request]

jobs:
  build:
    name: Vite Plugin Ruby

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.1

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}

      - run: pnpm -C vite-plugin-ruby install --frozen-lockfile

      - name: Build
        run: pnpm -C vite-plugin-ruby build

      - name: Test
        run: pnpm -C vite-plugin-ruby test
