name: Rubocop

on: [push, pull_request]

jobs:
  build:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Rubocop
        run: bin/rubocop
